fix docker run scripts

diff --git a/templates/resources/includes/xl-deploy-run-script.j2 b/templates/resources/includes/xl-deploy-run-script.j2
--- a/templates/resources/includes/xl-deploy-run-script.j2
+++ b/templates/resources/includes/xl-deploy-run-script.j2
@@ -1,41 +1,45 @@
 # Copy default plugins
 if [ -z "$(ls -A ${APP_HOME}/plugins)" ]; then
   echo "Empty ${APP_HOME}/plugins directory detected:"
-  echo "... Copying default plugins from ${APP_HOME}/default-plugins"
-
-  cd ${APP_HOME}/default-plugins
-  for pluginjar in *; do
-    pluginbasename=${pluginjar%%-[0-9\.]*.jar}
-    if [ -f ${APP_HOME}/plugins/*/$pluginbasename-[0-9\.]*.jar ]; then
-      echo "... Not copying $pluginrepo/$pluginjar because a version of that plugin already exists in the plugins directory"
-    else
-      cp -R ${APP_HOME}/default-plugins/$pluginrepo/$pluginjar ${APP_HOME}/plugins/$pluginrepo/
-    fi
-  done
-  cd ${APP_HOME}
-
-  echo "Done"
 fi
+  
+echo "... Copying default plugins from ${APP_HOME}/default-plugins to ${APP_HOME}/plugins when a plugin is missing"
+
+cd ${APP_HOME}/default-plugins
+for pluginjar in *; do
+  pluginbasename=${pluginjar%%-[0-9\.]*.xldp}
+  if [ -f ${APP_HOME}/plugins/$pluginbasename-[0-9\.]*.xldp ]; then
+    echo "... Not copying $pluginjar because a version of that plugin already exists in the plugins directory"
+  else
+    echo "... Copying $pluginjar to the plugins directory"
+    cp -R ${APP_HOME}/default-plugins/$pluginjar ${APP_HOME}/plugins/
+  fi
+done
+cd ${APP_HOME}
+echo "Done copying default plugins"
+
+
+# copy default configurations
+echo "... Copying default configuration from ${APP_HOME}/default-conf"
+
+cd ${APP_HOME}/default-conf
+for f in *; do
+  if [[ $f == *.template ]]; then
+    continue
+  fi
+  if [ -f ${APP_HOME}/conf/$f ]; then
+    echo "... Not copying $f because it already exists in the conf directory"
+  else
+    echo "... Copying $f to the conf directory"
+    cp -R $f ${APP_HOME}/conf/
+  fi
+done
+cd ${APP_HOME}
+echo "Done copying default configurations"
 
 # Set up new installation
 if [ ! -f "${APP_HOME}/conf/{{ boot_conf }}" ]; then
   echo "No ${APP_HOME}/conf/{{ boot_conf }} file detected:"
-  echo "... Copying default configuration from ${APP_HOME}/default-conf"
-
-  cd ${APP_HOME}/default-conf
-  for f in *; do
-    if [[ $f == *.template ]]; then
-      continue
-    fi
-    if [ -f ${APP_HOME}/conf/$f ]; then
-      echo "... Not copying $f because it already exists in the conf directory"
-    else
-      cp -R $f ${APP_HOME}/conf/
-    fi
-  done
-  cd ${APP_HOME}
-
-  echo "Done"
 
   if [ $# -eq 0 ] || [ $1 == "worker" ]; then
     echo "No arguments passed to container:"
@@ -54,6 +58,10 @@ if [ ! -f "${APP_HOME}/conf/{{ boot_conf }}" ]; then
       echo "... Generating repository keystore"
       keytool -genseckey -alias deployit-passsword-key -keyalg aes -keysize 128 -keypass "deployit" -keystore ${APP_HOME}/conf/repository-keystore.jceks -storetype jceks -storepass ${REPOSITORY_KEYSTORE_PASSPHRASE}
     else
+      if [ "${REPOSITORY_KEYSTORE_PASSPHRASE}" = "" ]; then
+        echo "REPOSITORY_KEYSTORE provided, without an accompanying passphrase. exiting..."
+        exit 1
+      fi
       echo ${REPOSITORY_KEYSTORE} | base64 -d > ${APP_HOME}/conf/repository-keystore.jceks
     fi
 
