S-111472 Introduce new slim images (#228)
* S-111472 Introduce new slim images

- Add new mount points for drivers
- Modify wrapper files to include drivers in classpath
- Introduce new slim tag which will not have any thirdparty db drivers except postgresql

* Build and push slim images

* Update commit method to push slim files

* S-111472 support slim for Deploy images and remove skip_vulnerable_libs

* S-111472 fixing DB and MQ configuration for the Deploy

---------

Co-authored-by: Vedran Pugar <vedran.pugar@digital.ai>

diff --git a/templates/resources/common/bin/run-in-container.sh.j2 b/templates/resources/common/bin/run-in-container.sh.j2
--- a/templates/resources/common/bin/run-in-container.sh.j2
+++ b/templates/resources/common/bin/run-in-container.sh.j2
@@ -19,52 +19,94 @@ function check_eula {
   fi;
 }
 
+check_files_exist() {
+    if ls $1 1> /dev/null 2>&1; then
+        return 1
+    else
+        return 0
+    fi
+}
+
+{%- if 'xl-release' not in product %}
 function copy_mq_driver {
   case ${XLD_TASK_QUEUE_DRIVER_CLASS_NAME} in
     *rabbitmq*)
-      echo "Detected RabbitMQ configuration. Copying required drivers to the lib folder."
-      cp ${APP_ROOT}/mq-libs/rabbitmq-jms* ${APP_HOME}/lib
-      cp ${APP_ROOT}/mq-libs/amqp-client* ${APP_HOME}/lib
+      echo "Detected RabbitMQ configuration. Copying required drivers to the driver/mq folder."
+      cp ${APP_ROOT}/mq-libs/rabbitmq-jms* ${APP_HOME}/driver/mq
+      cp ${APP_ROOT}/mq-libs/amqp-client* ${APP_HOME}/driver/mq
       ;;
     *activemq*)
-      echo "Detected ActiveMQ configuration. Copying required drivers to the lib folder."
-      cp ${APP_ROOT}/mq-libs/activemq* ${APP_HOME}/lib
+      echo "Detected ActiveMQ configuration. Copying required drivers to the driver/mq folder."
+      cp ${APP_ROOT}/mq-libs/activemq* ${APP_HOME}/driver/mq
       ;;
     *)
       echo "MQ Provider could not be inferred from url '${XLD_TASK_QUEUE_DRIVER_CLASS_NAME}'"
       ;;
   esac
 }
+{%- endif %}
 
 function copy_db_driver {
   echo "Copying a database driver"
 
   case ${XL_DB_URL} in
     jdbc:h2:*)
-      cp ${APP_ROOT}/db-libs/h2* ${APP_HOME}/lib
+      {%- if is_slim %}
+      echo "h2 jdbc driver is not provided by default in the classpath, please make sure you provide one. Please refer readme for more details"
+      {%- else %}
+      if check_files_exist "${APP_HOME}/lib/h2*.jar"; then
+        if check_files_exist "${APP_HOME}/driver/jdbc/h2*.jar"; then
+          echo "Detected H2 configuration. Copying required drivers to the driver/jdbc folder."
+          cp ${APP_ROOT}/db-libs/h2* ${APP_HOME}/driver/jdbc
+        fi
+      else
+        echo "h2 jdbc driver is provided by default in the classpath"
+      fi
+      {%- endif %}
       ;;
     jdbc:derby:*)
-      echo "Derby jdbc driver is provided by default in the classpath"
+      {%- if is_slim %}
+      echo "derby jdbc driver is not provided by default in the classpath, please make sure you provide one. Please refer readme for more details"
+      {%- else %}
+      echo "derby jdbc driver is provided by default in the classpath"
+      {%- endif %}
       ;;
     jdbc:oracle:*)
       echo "oracle jdbc driver is not provided by default in the classpath, please make sure you provide one. Please refer readme for more details"
       ;;
     jdbc:mysql:*)
-      cp ${APP_ROOT}/db-libs/mysql* ${APP_HOME}/lib
+      {%- if is_slim %}
+      echo "mysql jdbc driver is not provided by default in the classpath, please make sure you provide one. Please refer readme for more details"
+      {%- else %}
+      if check_files_exist "${APP_HOME}/driver/jdbc/mysql*.jar"; then
+        echo "Detected Mysql configuration. Copying required drivers to the driver/jdbc folder."
+        cp ${APP_ROOT}/db-libs/mysql* ${APP_HOME}/driver/jdbc
+      fi
+      {%- endif %}
       ;;
     jdbc:postgresql:*)
-      cp ${APP_ROOT}/db-libs/postgresql* ${APP_HOME}/lib
+      if check_files_exist "${APP_HOME}/driver/jdbc/postgresql*.jar"; then
+        echo "Detected Postgresql configuration. Copying required drivers to the driver/jdbc folder."
+        cp ${APP_ROOT}/db-libs/postgresql* ${APP_HOME}/driver/jdbc
+      fi
       ;;
     jdbc:sqlserver:*)
-      cp ${APP_ROOT}/db-libs/mssql* ${APP_HOME}/lib
+      {%- if is_slim %}
+      echo "sqlserver jdbc driver is not provided by default in the classpath, please make sure you provide one. Please refer readme for more details"
+      {%- else %}
+      if check_files_exist "${APP_HOME}/driver/jdbc/mssql*.jar"; then
+        echo "Detected SQLServer configuration. Copying required drivers to the driver/jdbc folder."
+        cp ${APP_ROOT}/db-libs/mssql* ${APP_HOME}/driver/jdbc
+      fi
+      {%- endif %}
       ;;
     jdbc:db2:*)
       echo "db2 jdbc driver is not provided by default in the classpath, please make sure you provide one. Please refer readme for more details"
       ;;
     *)
-        echo "Database type could not be inferred from url '${XL_REPO_DB_URL}', supported db types are 'h2', 'derby', 'oracle', 'mysql', 'postgresql', 'sqlserver', 'db2'"
-        exit 1
-        ;;
+      echo "Database type could not be inferred from url '${XL_REPO_DB_URL}', supported db types are 'h2', 'derby', 'oracle', 'mysql', 'postgresql', 'sqlserver', 'db2'"
+      exit 1
+      ;;
   esac
 }
 
@@ -76,11 +118,11 @@ function set_db_driver {
       XL_DB_DRIVER="org.h2.Driver"
       ;;
     jdbc:derby:*)
-      {% if new_derby %}
-        XL_DB_DRIVER="org.apache.derby.iapi.jdbc.AutoloadedDriver"
-      {% else %}
-        XL_DB_DRIVER="org.apache.derby.jdbc.AutoloadedDriver"
-      {% endif %}
+      {%- if new_derby %}
+      XL_DB_DRIVER="org.apache.derby.iapi.jdbc.AutoloadedDriver"
+      {%- else %}
+      XL_DB_DRIVER="org.apache.derby.jdbc.AutoloadedDriver"
+      {%- endif %}
       ;;
     jdbc:oracle:*)
       XL_DB_DRIVER="oracle.jdbc.OracleDriver"
@@ -244,12 +286,14 @@ function set_force_remove_missing_types {
 
 set_db_driver
 
-{% if 'central-config' not in product %}
-    check_eula
-    copy_db_driver
-    copy_mq_driver
-    store_license
-{% endif %}
+{%- if 'central-config' not in product %}
+check_eula
+copy_db_driver
+{%- if 'xl-release' not in product %} 
+copy_mq_driver 
+{%- endif %}
+store_license
+{%- endif %}
 
 generate_product_conf
 generate_node_conf
